// Generated by tools/build_pages.py from i18n/strings.json. Do not edit by hand.
export const STRINGS = {
    "meta.description": {
        "en": "Kalq turns a part's geometry into one technical truth and two separate commercial engines, for buyers and suppliers of manufactured parts.",
        "de": "Kalq macht aus der Geometrie eines Teils eine technische Wahrheit und zwei getrennte kommerzielle Engines, für Einkäufer und Lieferanten von Fertigungsteilen."
    },
    "title.impressum": {
        "en": "Kalq | Legal notice",
        "de": "Kalq | Impressum"
    },
    "title.datenschutz": {
        "en": "Kalq | Privacy policy",
        "de": "Kalq | Datenschutz"
    },
    "aria.home": {
        "en": "Kalq home",
        "de": "Kalq Startseite"
    },
    "aria.language": {
        "en": "Language",
        "de": "Sprache"
    },
    "aria.menu": {
        "en": "Main menu",
        "de": "Hauptmenü"
    },
    "aria.menuOpen": {
        "en": "Open menu",
        "de": "Menü öffnen"
    },
    "aria.menuClose": {
        "en": "Close menu",
        "de": "Menü schließen"
    },
    "nav.home": {
        "en": "Home",
        "de": "Start"
    },
    "nav.platform": {
        "en": "Platform",
        "de": "Plattform"
    },
    "nav.company": {
        "en": "Company",
        "de": "Unternehmen"
    },
    "footer.heading1": {
        "en": "Prove it on",
        "de": "Der Beweis"
    },
    "footer.heading2": {
        "en": "real parts",
        "de": "am echten Teil"
    },
    "footer.sub": {
        "en": "We are starting with CNC turned parts in Germany. If you buy or make them, apply for the pilot.",
        "de": "Wir starten mit CNC-Drehteilen in Deutschland. Wenn Sie solche Teile einkaufen oder fertigen, bewerben Sie sich für das Pilotprojekt."
    },
    "footer.pilot": {
        "en": "Apply for the pilot",
        "de": "Für das Pilotprojekt bewerben"
    },
    "footer.impressum": {
        "en": "Legal notice",
        "de": "Impressum"
    },
    "footer.privacy": {
        "en": "Privacy",
        "de": "Datenschutz"
    },
    "legal.lead": {
        "en": "Information pursuant to § 5 DDG",
        "de": "Angaben gemäß § 5 DDG"
    },
    "legal.provider": {
        "en": "Provider",
        "de": "Anbieter"
    },
    "legal.company": {
        "en": "[TODO: Company name]",
        "de": "[TODO: Firmenname]"
    },
    "legal.street": {
        "en": "[TODO: Street and number]",
        "de": "[TODO: Straße und Hausnummer]"
    },
    "legal.city": {
        "en": "[TODO: Postcode and city]",
        "de": "[TODO: PLZ und Ort]"
    },
    "legal.country": {
        "en": "[TODO: Country]",
        "de": "[TODO: Land]"
    },
    "legal.representedBy": {
        "en": "Represented by",
        "de": "Vertreten durch"
    },
    "legal.director": {
        "en": "[TODO: Managing director]",
        "de": "[TODO: Geschäftsführung]"
    },
    "legal.contact": {
        "en": "Contact",
        "de": "Kontakt"
    },
    "legal.email": {
        "en": "Email:",
        "de": "E-Mail:"
    },
    "legal.register": {
        "en": "Register entry",
        "de": "Registereintrag"
    },
    "legal.court": {
        "en": "Register court: [TODO]",
        "de": "Registergericht: [TODO]"
    },
    "legal.number": {
        "en": "Register number: [TODO]",
        "de": "Registernummer: [TODO]"
    },
    "legal.vat": {
        "en": "VAT ID",
        "de": "Umsatzsteuer-ID"
    },
    "legal.vatText": {
        "en": "VAT identification number pursuant to § 27a of the German VAT Act: [TODO]",
        "de": "Umsatzsteuer-Identifikationsnummer gemäß § 27a Umsatzsteuergesetz: [TODO]"
    },
    "privacy.title": {
        "en": "Privacy policy",
        "de": "Datenschutzerklärung"
    },
    "privacy.text": {
        "en": "[TODO: insert privacy policy]",
        "de": "[TODO: Datenschutztext einfügen]"
    }
};
